### ISSUE TITLE
Изменить парсинг локации

### ISSUE THREAD

**Issue by cullfy** [IBI-s-IT/ibi-lounge-backend#13]
Добавить поля аудитории в `additionals`

- адрес
- номер аудитории

возможно позже будет добавление поля ссылки на поиск аудитории?

**Comment by gbowsky** [comment]
МС-XX - понятно
А что делать с Н-XXX-X?

**Comment by cullfy** [comment]
### Информация по образованию номеров аудиторий:


- Начало **обязательное**
    - `МС` - малая садовая, тут все аудитории наши, тут всё просто
    - `Н` - невский, большая часть используются чтоб было заполнено поле аудитории для онлайн пар
      - Есть исключение для аудиторий на невском, в скором времени будут аудитории `Н-425`, `Н-430`, к ним так же подготовят видосики
- Номер **обязательное**
  - Номер аудитории, может быть вида: `XX`, `XX-X`, `XXX`, `XXX-X`
    - в идеале надо бы создать мапу, где номера будут уникальными ключами
- Окончание
  - `К` в конце означает что это компьютерная аудитория

**Comment by gbowsky** [comment]
отдельным полем сделаю
