### ISSUE TITLE
Исправить ошибку в сообщении приветствия.

### ISSUE THREAD

**Issue by cullfy** [IBI-s-IT/ibi-lounge-backend#14]
В приветствии, которое следует в боте после команды `/start` есть строчка `Привет, <tag>`

ошибка заключается в том что не у всех пользователей телеграма есть тег, если бота вызывает такой человек, следует следующая ошибочка:

![Image](https://github.com/IBI-s-IT/ibi-lounge-backend/assets/107591300/a4881a10-1b15-4955-b148-8c7af57b1dfe)

Предлагаю сделать вывод имени, если нет тега

**Comment by gbowsky** [comment]
будет исправлено в v2
